CREATE DATABASE IF NOT EXISTS logicaviva
CHARACTER SET UTF8MB4
COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE IF NOT EXISTS tb_users (
	userId int NOT NULL AUTO_INCREMENT,
   userName VARCHAR(25) NOT NULL,
   userEmail VARCHAR(100) NOT NULL,
   passwordHash TEXT NOT NULL,
   PRIMARY KEY (userId)
) ENGINE = INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE IF NOT EXISTS tb_log (
	id_log INT NOT NULL AUTO_INCREMENT,
   data_hora_log DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   tabela_afetada VARCHAR(100) NOT NULL,
   operacao VARCHAR(20) NOT NULL,
   descricao_log TEXT,
   usuario_log VARCHAR(100),
   PRIMARY KEY (id_log)
) ENGINE = INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;
